/**
 * Chinese labels for FPMS Demo UI
 * Centralized string table — no i18n framework needed
 */
export const ZH = {
    app: {
        name: '法务流程',
        subtitle: '知识产权管理系统',
    },
    login: {
        title: '系统登录',
        username: '用户名',
        password: '密码',
        submit: '登 录',
        error: '用户名或密码错误',
    },
    nav: {
        dashboard: '工作台',
        caseGroup: '案件管理',
        cases: '案件列表',
        documents: '文档管理',
        fees: '费用管理',
        billing: '账单管理',
        tasks: '期限监控',
        taskList: '任务列表',
        todayReminders: '今日提醒',
        clientGroup: '客户中心',
        clients: '客户列表',
        settingsGroup: '系统设置',
        templates: '模板管理',
        letterheads: '信头管理',
        systemParams: '系统参数',
        feeRates: '费率设置',
    },
    header: {
        searchPlaceholder: '搜索案件、客户...',
        logout: '退出登录',
    },
    dashboard: {
        title: '工作台',
    },
    route: {
        dashboard: '工作台',
        cases: '案件列表',
        case_new: '新建案件',
        case_detail: '案件详情',
        case_edit: '编辑案件',
        documents: '文档列表',
        document_new: '新建文档',
        document_detail: '文档详情',
        document_edit: '编辑文档',
        tasks: '任务列表',
        task_new: '新建任务',
        tasks_today: '今日提醒',
        fee_drafts: '费用草稿',
        fee_draft_new: '新建草稿',
        fee_draft_detail: '草稿详情',
        fee_rates: '费率设置',
        bills: '账单列表',
        bill_new: '新建账单',
        bill_detail: '账单详情',
        payments: '收款列表',
        payment_new: '新建收款',
        clients: '客户列表',
        client_new: '新建客户',
        client_edit: '编辑客户',
        settings_clients: '客户管理',
        system_templates: '模板管理',
        system_params: '系统参数',
        system_letterheads: '信头管理',
        focus_demo: '沉浸模式',
    },
    common: {
        create: '新建',
        edit: '编辑',
        delete: '删除',
        save: '保存',
        cancel: '取消',
        back: '返回',
        loading: '加载中...',
        empty: '暂无数据',
        confirm: '确认',
        search: '搜索',
        actions: '操作',
        status: '状态',
        refresh: '刷新',
        view: '查看',
        total: '共 {n} 条',
        goBack: '返回',
        noContent: '暂无内容',
    },
    detail: {
        back: '返回',
        quickActions: '快捷操作',
        overview: '概览',
    },
    caseDetail: {
        editCase: '编辑案件',
        overview: '概览',
        claims: '权利要求',
        officialDocs: '官方文件',
        fees: '费用',
        billing: '账单',
        tasks: '任务',
        caseInfo: '案件信息',
        caseNumber: '案号',
        title: '标题',
        client: '客户',
        status: '状态',
        filingDate: '申请日',
        appDate: '优先权日',
        notes: '备注',
        inventors: '发明人',
        quickActions: '快捷操作',
        quickEdit: '快速编辑',
        notFound: '未找到案件',
        notFoundMsg: '请求的案件不存在。',
        untitled: '未命名案件',
        claimsPlaceholder: '权利要求内容将在后续任务中实现。',
        docsPlaceholder: '官方文件将在后续任务中实现。',
        feesPlaceholder: '费用管理将在后续任务中实现。',
        tasksPlaceholder: '任务管理将在后续任务中实现。',
    },
    docDetail: {
        editDoc: '编辑文档',
        docContent: '文档内容',
        docInfo: '文档信息',
        id: '编号',
        direction: '方向',
        created: '创建时间',
        updated: '更新时间',
        quickActions: '快捷操作',
        notFound: '未找到文档',
        notFoundMsg: '请求的文档不存在。',
        noContent: '该文档暂无内容。',
    },
    feeDetail: {
        refresh: '刷新',
        lock: '锁定',
        unlock: '解锁',
        items: '明细',
        overview: '概览',
        draftMeta: '草稿信息',
        draftId: '草稿编号',
        status: '状态',
        caseId: '案件编号',
        clientId: '客户编号',
        draftType: '类型',
        currency: '币种',
        quickActions: '快捷操作',
        newDraft: '新建草稿',
        openCase: '打开案件',
        notFound: '未找到草稿',
        notFoundMsg: '请求的费用草稿不存在。',
        feeDraft: '费用草稿',
        lockedNotice: '此草稿已锁定，解锁后方可编辑。',
        lockConfirm: '锁定此草稿后将无法编辑，直到解锁。是否继续？',
        lockTitle: '锁定草稿',
        unlockConfirm: '解锁此草稿后可以继续编辑。是否继续？',
        unlockTitle: '解锁草稿',
        lockSuccess: '草稿已锁定',
        unlockSuccess: '草稿已解锁',
    },
    billDetail: {
        printBill: '打印账单',
        refresh: '刷新',
        items: '明细',
        overview: '概览',
        billItems: '账单明细',
        description: '描述',
        qty: '数量',
        unitPrice: '单价',
        amount: '金额',
        total: '合计',
        billInfo: '账单信息',
        billNo: '账单号',
        status: '状态',
        client: '客户',
        case_: '案件',
        currency: '币种',
        issueDate: '开票日',
        dueDate: '到期日',
        notes: '备注',
        amounts: '金额',
        balance: '余额',
        quickActions: '快捷操作',
        openCase: '打开案件',
        viewClient: '查看客户',
        notFound: '未找到账单',
        notFoundMsg: '请求的账单不存在。',
        noItems: '暂无账单明细。',
        downloadSuccess: '账单下载成功',
        templateNotConfigured: '账单模板未配置，请在系统设置中配置模板。',
    },
    caseList: {
        title: '案件列表',
        titleFiltered: '案件列表 · {name}',
        newCase: '新建案件',
        id: '编号',
        caseNo: '案号',
        caseTitle: '标题',
        client: '客户',
        status: '状态',
        updated: '更新时间',
        actions: '操作',
        view: '查看',
        emptyTitle: '暂无案件',
        emptyMsg: '创建您的第一个案件。',
        clearFilter: '清除阶段筛选',
        filterSubtitle: '共 {n} 件，均处于{step}',
    },
    taskList: {
        title: '任务列表',
        newTask: '新建任务',
        id: '编号',
        taskTitle: '标题',
        case_: '案件',
        status: '状态',
        priority: '优先级',
        dueDate: '截止日期',
        assigned: '负责人',
        actions: '操作',
        close: '关闭',
        reopen: '重新打开',
        cancel: '取消',
        emptyTitle: '暂无任务',
        emptyMsg: '当前没有任务。',
        closeConfirm: '确定要关闭"{title}"吗？',
        closeTitle: '关闭任务',
        reopenConfirm: '确定要重新打开"{title}"吗？',
        reopenTitle: '重新打开任务',
        cancelConfirm: '确定要取消"{title}"吗？此操作可能无法撤销。',
        cancelTitle: '取消任务',
        actionSuccess: '任务{action}成功',
    },
    billList: {
        title: '账单列表',
        newBill: '新建账单',
        billNo: '账单号',
        client: '客户',
        status: '状态',
        amount: '金额',
        balance: '余额',
        issueDate: '开票日',
        emptyTitle: '暂无账单',
        emptyMsg: '账单创建后将显示在此处。',
    },
    feeList: {
        title: '费用草稿',
        newDraft: '新建草稿',
        draftId: '草稿编号',
        case_: '案件',
        client: '客户',
        currency: '币种',
        status: '状态',
        amount: '金额',
        actions: '操作',
        view: '查看',
        emptyTitle: '暂无费用草稿',
        emptyMsg: '创建您的第一个草稿以开始跟踪费用。',
    },
    docList: {
        title: '文档列表',
        newDoc: '新建文档',
        id: '编号',
        direction: '方向',
        docTitle: '标题',
        case_: '案件',
        type: '类型',
        date: '日期',
        created: '创建时间',
        actions: '操作',
        view: '查看',
        emptyTitle: '暂无文档',
        emptyMsg: '创建您的第一个文档。',
    },
    pipeline: {
        newCases: '新委托',
        pendingTasks: '待办任务',
        urgentSuffix: '绝限',
        unbilledDrafts: '待出账草稿',
        unallocated: '待核销',
    },
    workflow: {
        title: '案件流程步骤（受理→初审→公布→实审→授权）',
        viewAll: '查看全部案件',
        summaryTotal: '当前共 {n} 件案件在主干流程中',
        summaryHint: '点击任一阶段卡查看列表',
        stageTitle: '阶段案件列表',
        stageTitleFiltered: '阶段案件列表：{name}',
        stageTitleAll: '阶段案件列表：全部',
        enterFullList: '进入完整列表',
        percent: '占比 {n}%',
        clickToView: '点击查看',
        noData: '暂无该阶段案件',
        colCaseNo: '案号',
        colClient: '客户',
        colTitle: '案件名称',
        colStep: '当前步骤',
        colStatus: '法律状态',
        colAction: '操作',
        colFilingDate: '申请日',
        colOwner: '负责人',
        viewDetail: '查看详情',
    },
    stepper: {
        currentStep: '当前步骤',
        stepIndex: '步骤序号',
        legalStatus: '法律状态',
        nextAction: '下一动作',
    },
    deadline: {
        title: '绝限提醒',
        noDeadline: '暂无绝限',
    },
    relatedTasks: {
        title: '关联任务',
        noTasks: '暂无任务',
    },
    actionCenter: {
        title: '待办任务',
        viewAll: '查看全部 →',
        relDoc: '关联文书',
        relFee: '关联费用',
        deadlineUrgent: '绝限: 剩{n}天',
        deadlineWarn: '剩{n}天',
    },
    finance: {
        title: '财务状况',
        pendingOffset: '待核销',
        overdue: '已逾期{n}天',
        pending: '待付款',
        offsetLink: '→ 关联账单',
    },
    drawer: {
        title: '新建案件',
        client: '客户',
        caseType: '案件类型',
        caseTitle: '案件标题',
        cancel: '取消',
        create: '创建案件',
        caseTypeInv: '发明专利',
        caseTypeUtil: '实用新型',
        caseTypeDesign: '外观设计',
        clientPlaceholder: '搜索客户...',
        titlePlaceholder: '输入案件标题',
    },
} as const
